# BASIC PROGRAM CONFIGURATIONS
output_file: './data/output.log'
errorl_file: './error/error.log'

# PASSWORD/SECRETS CONFIGURATIONS
base64_chars: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/='
min_key_length: 40
max_key_length: 66
min_pass_length: 8
max_pass_length: 12
password_complexity: 8

# GREP/REGEX CONFIGURATIONS
grep_words: ['*pass*','*secret*','*auth*','*key*','*token*']
grep_word_occurrence: 1

# FILE/DIRECTORY CONFIGURATIONS
filetype: ['.*']

excluded_files: [
  # Picture File Extensions
        '.jpg', '.jpeg', '.png', '.gif', '.tif',
        '.tiff', '.psd', '.svg', '.bmp', '.ico',
  # Audio/Video File Extensions
        '.mp4', '.mp3', '.webm', '.wav', '.aiff',
        '.aac', '.wma', '.wpl', '.midi', '.mid',
        '.wmv', '.m4v', '.avi', '.flv', '.mov',
        '.mpg', '.mpeg',
  # Font File Extensions
        '.ttf', '.woff', '.eot', '.otf', '.fnt',
        '.fon',
  # OS File Extensions
        '.exe', '.dll', '.wll', '.bin', '.lnk',
        '.sys', '.deb', '.pkg', '.rpm'
  # MISC File Extensions
        '.css', '.DS_Store', '.pdf', '.ppt'
]

archive_files: [
        '.tar', '.tar.gz', '.tar.bz2', '.tbz',
        '.zip', '.7z', '.rar', '.tgz', '.z'
]

database_files: ['.db', '.dbf', '.mdb', '.sql', '.sqlite']

sensitive_files: [
        'unattend.xml',
        'sysprep.inf',
        'sysprep.xml',
        'web.config',
        'Groups.xml',
        'Services.xml',
        'ScheduledTasks.xml',
        'Printers.xml',
        'Drives.xml',
        'DataSources.xml',
        'SiteList.xml'
]

sensitive_full_path_files: [
  # Windows Sensitive Files
    # Panther File Locations
        'C:\unattend.xml',
        'C:\Windows\Panther\Unattend.xml',
        'C:\Windows\Panther\Unattend\Unattend.xml',
    # System Prep File Location
        'C:\Windows\System32\sysprep.inf',
        'C:\Windows\System32\sysprep\sysprep.xml',
    # Windows IIS File Location
        'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config',
        'C:\Windows\Microsoft.NET\Framework64\v2.0.50727\CONFIG\web.config',
        'C:\inetpub\wwwroot\web.config',
    # Windows Group Policy File Locations
        #'C:\ProgramData\Group Policy\History\????\Machine\Preferences\Groups\Groups.xml',
        #'\\????\SYSVOL\\Policies\????\MACHINE\Preferences\Groups\Groups.xml',
        #'C:\ProgramData\Group Policy\History\????\Machine\Preferences\Services\Services.xml',
        #'\\????\SYSVOL\\Policies\????\MACHINE\Preferences\Services\Services.xml',
        #'C:\ProgramData\Group Policy\History\????\Machine\Preferences\ScheduledTasks\ScheduledTasks.xml',
        #'\\????\SYSVOL\\Policies\????\MACHINE\Preferences\ScheduledTasks\ScheduledTasks.xml',
        #'C:\ProgramData\Group Policy\History\????\Machine\Preferences\Printers\Printers.xml',
        #'\\????\SYSVOL\\Policies\????\MACHINE\Preferences\Printers\Printers.xml',
        #'C:\ProgramData\Group Policy\History\????\Machine\Preferences\Drives\Drives.xml',
        #'\\????\SYSVOL\\Policies\????\MACHINE\Preferences\Drives\Drives.xml',
        #'C:\ProgramData\Group Policy\History\????\Machine\Preferences\DataSources\DataSources.xml',
        #'\\????\SYSVOL\\Policies\????\MACHINE\Preferences\DataSources\DataSources.xml',
  # Windows Third Party Software
    # McAfee - Stored Encrypted
       '%AllUsersProfile%Application Data\McAfee\Common Framework\SiteList.xml'
  # Unix/Linux Sensitive Files
        '.history',            # History File
]

sensitive_registry_keys: [
        'HKEY_LOCAL_MACHINE\SOFTWARE\RealVNC\WinVNC4', '/v password',                # Third-Party: VNC
        'HKEY_CURRENT_USER\Software\SimonTatham\PuTTY\Sessions',                     # Third-Party: PuTTY
        'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon',  # Windows Autologin
        'HKEY_LOCAL_MACHINE\SYSTEM\Current\ControlSet\Services\SNMP',                # SNMP Parameters
]


