# BASIC PROGRAM CONFIGURATIONS
output_file: './data/output.log'
errorl_file: './error/error.log'

# PASSWORD/SECRETS CONFIGURATIONS
base64_chars: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/='
min_key_length: 40
max_key_length: 66
min_pass_length: 8
max_pass_length: 12
password_complexity: 8

# GREP/REGEX CONFIGURATIONS
grep_words: ['*pass*','*secret*','*auth*','*key*','*token*']
grep_word_occurrence: 1

# FILE/DIRECTORY CONFIGURATIONS
filetype: ['.*']

excluded_files: [
  # Picture File Extensions
        '.jpg', '.jpeg', '.png', '.gif', '.tif',
        '.tiff', '.psd', '.svg', '.bmp', '.ico',
  # Audio/Video File Extensions
        '.mp4', '.mp3', '.webm', '.wav', '.aiff',
        '.aac', '.wma', '.wpl', '.midi', '.mid',
        '.wmv', '.m4v', '.avi', '.flv', '.mov',
        '.mpg', '.mpeg',
  # Font File Extensions
        '.ttf', '.woff', '.eot', '.otf', '.fnt',
        '.fon',
  # OS File Extensions
        '.exe', '.dll', '.wll', '.bin', '.lnk',
        '.sys',
  # MISC File Extensions
        '.css', '.DS_Store', '.pdf', '.ppt']

archive_files: [
        '.tar', '.tar.gz', '.tar.bz2', '.tbz',
        '.zip', '.7z', '.rar', '.tgz', '.deb',
        '.pkg', '.rpm', '.z']

database_files: ['.db', '.dbf', '.mdb', '.sql', '.sqlite']


